// referer: fonts. safe. 36x. cn
// fingerprint: a6 66 b6 90 46 44 d4 11
// 0 = free, 1 = licensed, -1 = unknown
var front = [
	{"lic":0, "desc":"幼圆", "source":"YouYuan"},
	{"lic":0, "desc":"宋体", "source":"SimSun"},
	{"lic":0, "desc":"黑体", "source":"SimHei"},
	{"lic":0, "desc":"楷体", "source":"KaiTi"},
	{"lic":0, "desc":"新宋体", "source":"NSimSun"},
	{"lic":0, "desc":"仿宋", "source":"FangSong"},
	{"lic":0, "desc":"隶书", "source":"LiSu"},
	{"lic":0, "desc":"思源黑体", "source":"Source Han Sans CN"},
	{"lic":0, "desc":"思源宋体", "source":"Source Han Serif SC"},
	{"lic":0, "desc":"文泉驿微米黑", "source":"WenQuan Yi Micro Hei"},
	{"lic":0, "desc":"Times New Roman", "source":"Times New Roman"},
	{"lic":1, "desc":"微软正黑体", "source":"Microsoft JhengHei"},
	{"lic":1, "desc":"苹方", "source":"PingFang SC"},
	{"lic":1, "desc":"华康翩翩体", "source":"Hanzipen SC"},
	{"lic":1, "desc":"华康手札体", "source":"Hannotate SC"},
	{"lic":1, "desc":"汉仪楷体", "source":"HYKaiti"},
	{"lic":1, "desc":"Arial Unicode MS", "source":"Arial"},
	{"lic":1, "desc":"微软雅黑", "source":"Microsoft Yahei"},
	{"lic":1, "desc":"华文黑体", "source":"STHeiti"},
	{"lic":1, "desc":"华文楷体", "source":"STKaiti"},
	{"lic":1, "desc":"华文宋体", "source":"STSong"},
	{"lic":1, "desc":"华文仿宋", "source":"STFangsong"},
	{"lic":1, "desc":"华文中宋", "source":"STZhongsong"},
	{"lic":1, "desc":"华文琥珀", "source":"STHupo"},
	{"lic":1, "desc":"华文新魏", "source":"STXinwei"},
	{"lic":1, "desc":"华文隶书", "source":"STLiti"},
	{"lic":1, "desc":"华文行楷", "source":"STXingkai"},
	{"lic":1, "desc":"冬青黑体简", "source":"Hiragino Sans GB"},
	{"lic":1, "desc":"兰亭黑-简", "source":"Lantinghei SC"},
	{"lic":1, "desc":"华文细黑", "source":"STXihei"},
	{"lic":1, "desc":"华文彩云", "source":"STCaiyun"},
	{"lic":1, "desc":"方正舒体", "source":"FZShuTi"},
	{"lic":1, "desc":"方正姚体", "source":"FZYaoti"},
	{"lic":1, "desc":"汉仪旗黑", "source":"HYQihei 40S"},
	{"lic":1, "desc":"汉仪旗黑", "source":"HYQihei 50S"},
	{"lic":1, "desc":"汉仪旗黑", "source":"HYQihei 60S"},
	{"lic":1, "desc":"汉仪大宋简", "source":"HYDaSongJ"},
	{"lic":1, "desc":"汉仪家书简", "source":"HYJiaShuJ"},
	{"lic":1, "desc":"汉仪PP体简", "source":"HYPPTiJ"},
	{"lic":1, "desc":"汉仪乐喵体简", "source":"HYLeMiaoTi"},
	{"lic":1, "desc":"汉仪小麦体", "source":"HYXiaoMaiTiJ"},
	{"lic":1, "desc":"汉仪程行简", "source":"HYChengXingJ"},
	{"lic":1, "desc":"汉仪黑荔枝", "source":"HYHeiLiZhiTiJ"},
	{"lic":1, "desc":"汉仪雅酷黑W", "source":"HYYaKuHeiW"},
	{"lic":1, "desc":"汉仪大黑简", "source":"HYDaHeiJ"},
	{"lic":1, "desc":"方正粗雅宋简体", "source":"FZYaSongS-B-GB"},
	{"lic":1, "desc":"方正报宋简体", "source":"FZBaoSong-Z04S"},
	{"lic":1, "desc":"方正粗圆简体", "source":"FZCuYuan-M03S"},
	{"lic":1, "desc":"方正大标宋简体", "source":"FZDaBiaoSong-B06S"},
	{"lic":1, "desc":"方正大黑简体", "source":"FZDaHei-B02S"},
	{"lic":1, "desc":"方正仿宋简体", "source":"FZFangSong-Z02S"},
	{"lic":1, "desc":"方正黑体简体", "source":"FZHei-B01S"},
	{"lic":1, "desc":"方正琥珀简体", "source":"FZHuPo-M04S"},
	{"lic":1, "desc":"方正楷体简体", "source":"FZKai-Z03S"},
	{"lic":1, "desc":"方正隶变简体", "source":"FZLiBian-S02S"},
	{"lic":1, "desc":"方正隶书简体", "source":"FZLiShu-S01S"},
	{"lic":1, "desc":"方正美黑简体", "source":"FZMeiHei-M07S"},
	{"lic":1, "desc":"方正书宋简体", "source":"FZShuSong-Z01S"},
	{"lic":1, "desc":"方正舒体简体", "source":"FZShuTi-S05S"},
	{"lic":1, "desc":"方正水柱简体", "source":"FZShuiZhu-M08S"},
	{"lic":1, "desc":"方正宋黑简体", "source":"FZSongHei-B07S"},
	{"lic":1, "desc":"方正宋三简体", "source":"FZSong"},
	{"lic":1, "desc":"方正魏碑简体", "source":"FZWeiBei-S03S"},
	{"lic":1, "desc":"方正细等线简体", "source":"FZXiDengXian-Z06S"},
	{"lic":1, "desc":"方正细黑一简体", "source":"FZXiHei I-Z08S"},
	{"lic":1, "desc":"方正细圆简体", "source":"FZXiYuan-M01S"},
	{"lic":1, "desc":"方正小标宋简体", "source":"FZXiaoBiaoSong-B05S"},
	{"lic":1, "desc":"方正行楷简体", "source":"FZXingKai-S04S"},
	{"lic":1, "desc":"方正姚体简体", "source":"FZYaoTi-M06S"},
	{"lic":1, "desc":"方正中等线简体", "source":"FZZhongDengXian-Z07S"},
	{"lic":1, "desc":"方正准圆简体", "source":"FZZhunYuan-M02S"},
	{"lic":1, "desc":"方正综艺简体", "source":"FZZongYi-M05S"},
	{"lic":1, "desc":"方正彩云简体", "source":"FZCaiYun-M09S"},
	{"lic":1, "desc":"方正隶二简体", "source":"FZLiShu II-S06S"},
	{"lic":1, "desc":"方正康体简体", "source":"FZKangTi-S07S"},
	{"lic":1, "desc":"方正超粗黑简体", "source":"FZChaoCuHei-M10S"},
	{"lic":1, "desc":"方正新报宋简体", "source":"FZNew BaoSong-Z12S"},
	{"lic":1, "desc":"方正新舒体简体", "source":"FZNew ShuTi-S08S"},
	{"lic":1, "desc":"方正黄草简体", "source":"FZHuangCao-S09S"},
	{"lic":1, "desc":"方正少儿简体", "source":"FZShaoEr-M11S"},
	{"lic":1, "desc":"方正稚艺简体", "source":"FZZhiYi-M12S"},
	{"lic":1, "desc":"方正细珊瑚简体", "source":"FZXiShanHu-M13S"},
	{"lic":1, "desc":"方正粗宋简体", "source":"FZCuSong-B09S"},
	{"lic":1, "desc":"方正平和简体", "source":"FZPingHe-S11S"},
	{"lic":1, "desc":"方正华隶简体", "source":"FZHuaLi-M14S"},
	{"lic":1, "desc":"方正瘦金书简体", "source":"FZShouJinShu-S10S"},
	{"lic":1, "desc":"方正细倩简体", "source":"FZXiQian-M15S"},
	{"lic":1, "desc":"方正中倩简体", "source":"FZZhongQian-M16S"},
	{"lic":1, "desc":"方正粗倩简体", "source":"FZCuQian-M17S"},
	{"lic":1, "desc":"方正胖娃简体", "source":"FZPangWa-M18S"},
	{"lic":1, "desc":"方正宋一简体", "source":"FZSongYi-Z13S"},
	{"lic":1, "desc":"方正剪纸简体", "source":"FZJianZhi-M23S"},
	{"lic":1, "desc":"方正流行体简体", "source":"FZLiuXingTi-M26S"},
	{"lic":1, "desc":"方正祥隶简体", "source":"FZXiangLi-S17S"},
	{"lic":1, "desc":"方正粗活意简体", "source":"FZCuHuoYi-M25S"},
	{"lic":1, "desc":"方正胖头鱼简体", "source":"FZPangTouYu-M24S"},
	{"lic":1, "desc":"方正卡通简体", "source":"FZKaTong-M19S"},
	{"lic":1, "desc":"方正艺黑简体", "source":"FZYiHei-M20S"},
	{"lic":1, "desc":"方正水黑简体", "source":"FZShuiHei-M21S"},
	{"lic":1, "desc":"方正古隶简体", "source":"FZGuLi-S12S"},
	{"lic":1, "desc":"方正幼线简体", "source":"FZYouXian-Z09S"},
	{"lic":1, "desc":"方正启体简体", "source":"FZQiTi-S14S"},
	{"lic":1, "desc":"方正小篆体", "source":"FZXiaoZhuanTi-S13T"},
	{"lic":1, "desc":"方正硬笔楷书简体", "source":"FZYingBiKaiShu-S15S"},
	{"lic":1, "desc":"方正毡笔黑简体", "source":"FZZhanBiHei-M22S"},
	{"lic":1, "desc":"方正硬笔行书简体", "source":"FZYingBiXingShu-S16S"},
	{"lic":1, "desc":"汉仪尚巍手书W", "source":"HYShangWeiShouShuW"},
	{"lic":1, "desc":"方正萌软体", "source":"FZMengRuanTiS"},
	{"lic":1, "desc":"方正萌艺体", "source":"FZMengYiTiS"},
	{"lic":1, "desc":"方正本墨绪圆体", "source":"FZBMXY JW"},
	{"lic":1, "desc":"方正晴朗体", "source":"FZQINGLANGTIS"},
	{"lic":1, "desc":"方正飞跃体", "source":"FZFeiYueTiS"},
	{"lic":1, "desc":"方正管峻楷书", "source":"FZGUANJUNKAISHUS"},
	{"lic":1, "desc":"方正方俊黑", "source":"FZFangJunHeiS"},
	{"lic":1, "desc":"方正仙阵体", "source":"FZXianZhenTiS"},
	{"lic":1, "desc":"方正记忆的碎片体", "source":"FZJiYiDeSuiPianTiS"},
	{"lic":1, "desc":"方正兵马俑体", "source":"FZBingMaYongTiS"},
	{"lic":1, "desc":"方正克书皇榜体", "source":"FZKeShuHuangBang"},
	{"lic":1, "desc":"方正清仿宋系列", "source":"FZQingFangSongS"},
	{"lic":1, "desc":"方正雅士黑", "source":"FZYaShiHeiS"},
	{"lic":1, "desc":"方正奇妙体", "source":"FZQiMTJ"},
	{"lic":1, "desc":"方正活龙体", "source":"FZHuoLTJ"},
	{"lic":1, "desc":"方正玩伴体系列", "source":"FZWanBTJ"},
	{"lic":1, "desc":"方正赞美体", "source":"FZZANMTJ"},
	{"lic":1, "desc":"方正苏新诗小爨", "source":"FZSuXinShiXiaoCuanS"},
	{"lic":1, "desc":"方正超重要体", "source":"FzCHAOZYTJW TTF"},
	{"lic":1, "desc":"方正锐正圆", "source":"FZRuiZhengYuanS"},
	{"lic":1, "desc":"方正悠宋简可变", "source":"FZYouSJ VF WT"},
	{"lic":1, "desc":"方正复古粗宋", "source":"FOUNDERTYPE"},
	{"lic":1, "desc":"方正邓黑隶", "source":"FZDengHLJ"},
	{"lic":1, "desc":"方正趣黑", "source":"FZQuHJW"},
	{"lic":1, "desc":"方正尚艺体", "source":"FZShangYiTiS"},
	{"lic":1, "desc":"方正秀麗", "source":"FZXiuLiB-Z13"},
	{"lic":1, "desc":"Serifa®", "source":"Serifa"},
	{"lic":1, "desc":"Serpentine™", "source":"Serpentine"},
	{"lic":1, "desc":"方正书宋", "source":"FZSS"},
	{"lic":1, "desc":"小美体", "source":"XIAOMEI JW"},
	{"lic":1, "desc":"方正字迹-颜振东楷", "source":"FZZJ-YZDKJW"},
	{"lic":1, "desc":"方正字迹-禚效锋行草", "source":"FZZJ-ZXFXCJW"},
	{"lic":1, "desc":"方正字迹-顾建平楷书", "source":"FZZJ-GJPKSJW"},
	{"lic":1, "desc":"方正字迹-顾建平隶书", "source":"FZZJ-GJPLSJF"},
	{"lic":1, "desc":"方正字迹-周密行楷", "source":"FZZJ-ZMXKJW"},
	{"lic":1, "desc":"方正字迹-自强魏楷体", "source":"FZZJ-ZQWKJW"},
	{"lic":1, "desc":"方正字迹-张二魁硬楷", "source":"FZZJ-ZEKYKJW"},
	{"lic":1, "desc":"方正字迹-曾柏求排笔", "source":"FZZJ-ZBQPBJW"},
	{"lic":1, "desc":"方正字迹-严祖喜行楷", "source":"FZZJ-YZXXKJW"},
	{"lic":1, "desc":"方正字迹-清代碑体", "source":"FZZJ-QDBTJW"},
	{"lic":1, "desc":"方正字迹-陶建华魏碑", "source":"FZZJ-TJHWBJW"},
	{"lic":1, "desc":"方正字迹-张亮硬笔行书", "source":"FZZJ-ZLYBXSJW"},
	{"lic":1, "desc":"方正字迹-长江行书", "source":"FZZJ-CJXSJW"},
	{"lic":1, "desc":"方正字迹-刘毅硬笔行书", "source":"FZZJ-LYYBXSJW"},
	{"lic":1, "desc":"方正字迹-叶根友特楷", "source":"YEGENYOUTEKAI"},
	{"lic":1, "desc":"方正字迹-刘毅硬笔楷书", "source":"FZZJ-LYYBKSJW"},
	{"lic":1, "desc":"方正字迹-吴进行书", "source":"FZZJ-WJXSJW"},
	{"lic":1, "desc":"方正字迹-刘宏楷书", "source":"FZZJ-LHKSJW"},
	{"lic":1, "desc":"方正字迹-陈光池楷书", "source":"FZZJ-CGCKSJW"},
	{"lic":1, "desc":"方正字迹-柳正枢行楷", "source":"FZZJ-LZSXKJW"},
	{"lic":1, "desc":"方正字迹-李凤武行书", "source":"FZZJ-LFWXSJW"},
	{"lic":1, "desc":"方正字迹-顧建平篆書", "source":"FZZJ-GJPZSFU"},
	{"lic":1, "desc":"Adelle Sans DEV", "source":"Adelle Sans"},
	{"lic":1, "desc":"Protipo", "source":"PROTIPO"},
	{"lic":1, "desc":"Maiola", "source":"Maiola"},
	{"lic":1, "desc":"Sanserata", "source":"Sanserata"},
	{"lic":1, "desc":"Lisbeth", "source":"Lisbeth"},
	{"lic":1, "desc":"Iro Sans", "source":"IRO SANS"},
	{"lic":1, "desc":"Athelas", "source":"Athelas"},
	{"lic":1, "desc":"Noort", "source":"NOORT"},
	{"lic":1, "desc":"Noam", "source":"NOAM"},
	{"lic":1, "desc":"Tablet Gothic", "source":"Tablet Gothic"},
	{"lic":1, "desc":"Essay", "source":"Essay Text"},
	{"lic":1, "desc":"AwanZaman", "source":"AwanZaman"},
	{"lic":1, "desc":"Fino Stencil", "source":"FINO STENCIL"},
	{"lic":1, "desc":"Fino", "source":"FINO"},
	{"lic":1, "desc":"Garalda", "source":"Garalda"},
	{"lic":1, "desc":"Iskra", "source":"Iskra"},
	{"lic":1, "desc":"Eskapade", "source":"Eskapade"},
	{"lic":1, "desc":"Karmina Sans", "source":"Karmina Sans"},
	{"lic":1, "desc":"Karmina", "source":"Karmina"},
	{"lic":1, "desc":"LFT Etica", "source":"LFT Etica"},
	{"lic":1, "desc":"Lipa Agate", "source":"Lipa Agate"},
	{"lic":1, "desc":"Marco", "source":"Marco"},
	{"lic":1, "desc":"Pollen", "source":"Pollen"},
	{"lic":1, "desc":"Ronnia", "source":"Ronnia"},
	{"lic":1, "desc":"Sirba", "source":"Sirba"},
	{"lic":1, "desc":"Soleil", "source":"Soleil"},
	{"lic":1, "desc":"Bely", "source":"BELY"},
	{"lic":1, "desc":"Bree Serif", "source":"Bree Serif"},
	{"lic":1, "desc":"Bree", "source":"Bree"},
	{"lic":1, "desc":"Capitolium2", "source":"Capitolium2"},
	{"lic":1, "desc":"Coranto 2", "source":"Coranto 2"},
	{"lic":1, "desc":"Cora", "source":"Cora"},
	{"lic":1, "desc":"Crete", "source":"Crete"},
	{"lic":1, "desc":"Ebony", "source":"Ebony"},
	{"lic":1, "desc":"Edita", "source":"Edita"},
	{"lic":1, "desc":"Givry", "source":"Givry"},
	{"lic":1, "desc":"Adelle Sans", "source":"Adelle Sans"},
	{"lic":1, "desc":"Abril", "source":"Abril"},
	{"lic":1, "desc":"Abril Titling", "source":"Abril Titling"},
	{"lic":1, "desc":"Adelle", "source":"Adelle"},
	{"lic":1, "desc":"Alize", "source":"Alize"},
	{"lic":1, "desc":"Adobe Gothic Std B", "source":"Adobe Gothic Std B"},
	{"lic":1, "desc":"Adobe Myungjo Std M", "source":"Adobe Myungjo Std M"},
	{"lic":1, "desc":"造字工房形黑体", "source":"MF XingHei(Noncommercial)"},
	{"lic":1, "desc":"造字工房力黑体", "source":"MF LiHei(Noncommercial)"},
	{"lic":1, "desc":"汉仪综艺体简", "source":"HYZongYiJ"},
	{"lic":1, "desc":"汉仪中宋简", "source":"HYZhongSongJ"},
	{"lic":1, "desc":"汉仪中隶书简", "source":"HYZhongLiShuJ"},
	{"lic":1, "desc":"汉仪中黑简", "source":"HYZhongHeiJ"},
	{"lic":1, "desc":"汉仪中等线简", "source":"HYZhongDengXianJ"},
	{"lic":1, "desc":"汉仪丫丫体简", "source":"HYYaYaJ"},
	{"lic":1, "desc":"汉仪雪君体简", "source":"HYXueJunJ"},
	{"lic":1, "desc":"汉仪雪峰体简", "source":"HYXueFengJ"},
	{"lic":1, "desc":"汉仪秀英体简", "source":"HYXiuYingJ"},
	{"lic":1, "desc":"汉仪醒示体简", "source":"HYXingShiJ"},
	{"lic":1, "desc":"汉仪行楷简", "source":"HYXingKaiJ"},
	{"lic":1, "desc":"汉仪娃娃纂简", "source":"HYWaWaZhuanJ"},
	{"lic":1, "desc":"汉仪书魂体检", "source":"HYShuHunJ"},
	{"lic":1, "desc":"汉仪漫步体间", "source":"HYManBuJ"},
	{"lic":1, "desc":"汉仪菱心体简", "source":"HYLingXinJ"},
	{"lic":1, "desc":"汉仪立黑简", "source":"HYLiHeiJ"},
	{"lic":1, "desc":"汉仪楷体简", "source":"HYKaiTiJ"},
	{"lic":1, "desc":"汉仪仿宋简", "source":"HYFangSongJ"},
	{"lic":1, "desc":"汉仪方叠体检", "source":"HYFangDieJ"},
	{"lic":1, "desc":"汉仪蝶语简体", "source":"HYDieYuJ"},
	{"lic":1, "desc":"汉仪长美黑简", "source":"HYChangMeiHeiJ"},
	{"lic":1, "desc":"方正字迹-童体硬笔字体", "source":"FZZJ-TTYBFONT"},
	{"lic":1, "desc":"方正字迹-豪放行书简体", "source":"FZZJ-HFXSJW"},
	{"lic":1, "desc":"方正正准黑简体", "source":"FZZhengHeiS-M-GB"},
	{"lic":1, "desc":"方正正纤黑简体", "source":"FZZhengHeiS-EL-GB"},
	{"lic":1, "desc":"方正正大黑简体", "source":"FZZhengHeiS-EB-GB"},
	{"lic":1, "desc":"方正正粗黑简体", "source":"FZZhengHeiS-B-GB"},
	{"lic":1, "desc":"方正藏意汉体简体", "source":"FZZangYiHanTiS-R-GB"},
	{"lic":1, "desc":"方正韵动特黑简体", "source":"FZYunDongHeiS-H-GB"},
	{"lic":1, "desc":"方正颜宋简体_粗", "source":"FZYanSongS-B-GB"},
	{"lic":1, "desc":"方正淘乐简体", "source":"FZTLJW"},
	{"lic":1, "desc":"方正粗谭黑简体", "source":"FZTanHeiS-B-GB"},
	{"lic":1, "desc":"方正孙拥声简体", "source":"FZSunYongShengS-R-GB"},
	{"lic":1, "desc":"方正水云简体", "source":"FZShuiYunS-EB-GB"},
	{"lic":1, "desc":"方正尚酷简体", "source":"FZShangKuS-R-GB"},
	{"lic":1, "desc":"方正启笛简体", "source":"FZQiDiS-R-GB"},
	{"lic":1, "desc":"方正品尚黑简体", "source":"FZPinShangHeiS-R-GB"},
	{"lic":1, "desc":"方正品尚粗黑简体", "source":"FZPinShangHeiS-B-GB"},
	{"lic":1, "desc":"方正喵呜简体", "source":"FZMiaoWuS-R-GB"},
	{"lic":1, "desc":"方正喵呜体", "source":"FZMiaoWuS-R-GB"},
	{"lic":1, "desc":"方正兰亭圆简体", "source":"FZLanTingYuanS-R-GB"},
	{"lic":1, "desc":"方正兰亭圆简体_纤", "source":"FZLanTingYuanS-EL-GB"},
	{"lic":1, "desc":"方正兰亭纤黑繁体", "source":"FZLanTingHeiT-EL-GB"},
	{"lic":1, "desc":"方正兰亭超细黑简体", "source":"FZLanTingHeiS-UL-GB"},
	{"lic":1, "desc":"方正兰亭黑简体", "source":"FZLanTingHeiS-R-GB"},
	{"lic":1, "desc":"方正兰亭特黑简体", "source":"FZLanTingHeiS-H-GB"},
	{"lic":1, "desc":"方正兰亭纤黑简体", "source":"FZLanTingHeiS-EL-GB"},
	{"lic":1, "desc":"方正兰亭细黑_GBK-M", "source":"FZLanTingHei-L-GBK-M"},
	{"lic":1, "desc":"方正兰亭细黑_GBK", "source":"FZLanTingHei-L-GBK"},
	{"lic":1, "desc":"方正静蕾简体", "source":"FZJingLeiS-R-GB"},
	{"lic":1, "desc":"方正汉真广标简体", "source":"FZHanZhenGuangBiaoS-GB"},
	{"lic":1, "desc":"方正大魏体简体", "source":"FZDaWeiTiS-R-GB"},
	{"lic":1, "desc":"方正博雅宋简体", "source":"FZBoYaSongS-GB"},
	{"lic":1, "desc":"Helvetica", "source":"Helvetica"},
	{"lic":1, "desc":"造字工房臻宋体", "source":"MF ZhenSong(Noncommercial)"},
	{"lic":1, "desc":"造字工房云宋体", "source":"MF YunSong(Noncommercial)"},
	{"lic":1, "desc":"造字工房锦宋体", "source":"MF JinSong(Noncommercial)"},
	{"lic":1, "desc":"造字工房卓黑体", "source":"MF ZhuoHei(Noncommercial)"},
	{"lic":1, "desc":"造字工房元黑体", "source":"MF YuanHei(Noncommercial)"},
	{"lic":1, "desc":"造字工房启黑体", "source":"MF QiHei(Noncommercial)"},
	{"lic":1, "desc":"造字工房鼎黑体", "source":"MF DingHei(Noncommercia)"},
	{"lic":1, "desc":"汉仪刚艺体", "source":"HYGangYiTi"},
	{"lic":1, "desc":"方正兰亭粗黑简体", "source":"FZLTCHJW"},
	{"lic":1, "desc":"造字工房版黑 G0v1", "source":"RTWS BanHei G0v1"},
	{"lic":1, "desc":"造字工房博黑", "source":"MF BoHei(Noncommercial)"},
	{"lic":1, "desc":"造字工房典黑", "source":"MF DianHei(Noncommercial)"},
	{"lic":1, "desc":"造字工房黄金时代", "source":"MF TheGoldenEra(Noncommercial)"},
	{"lic":1, "desc":"造字工房佳黑", "source":"MF JiaHei(Noncommercial)"},
	{"lic":1, "desc":"造字工房坚黑", "source":"MF JianHei(Noncommercial)"},
	{"lic":1, "desc":"造字工房劲黑 G0v1", "source":"RTWS JinHei G0v1"},
	{"lic":1, "desc":"造字工房郎宋 G0v1", "source":"RTWS LangSong G0v1"},
	{"lic":1, "desc":"造字工房力黑", "source":"MF LiHei(Noncommercial)"},
	{"lic":1, "desc":"造字工房凌黑", "source":"MF LingHei(Noncommercial)"},
	{"lic":1, "desc":"造字工房明黑", "source":"MF MingHei(Noncommercial)"},
	{"lic":1, "desc":"造字工房品宋", "source":"MF PinSong(Noncommercial)"},
	{"lic":1, "desc":"造字工房形黑", "source":"MF XingHei(Noncommercial)"},
	{"lic":1, "desc":"造字工房雅圆 G0v1", "source":"RTWS YaYuan G0v1"},
	{"lic":1, "desc":"造字工房哲黑", "source":"MF ZheHei(Noncommercial)"},
	{"lic":-1, "desc":"宋体-简", "source":"Songti SC"},
	{"lic":-1, "desc":"娃娃体-简", "source":"Wawati SC"},
	{"lic":-1, "desc":"魏碑-简", "source":"Weibei SC"},
	{"lic":-1, "desc":"行楷-简", "source":"Xingkai SC"},
	{"lic":-1, "desc":"雅痞-简", "source":"Yapi SC"},
	{"lic":-1, "desc":"圆体-简", "source":"Yuanti SC"},
	{"lic":-1, "desc":"Tahoma", "source":"tahoma"}
];
